### ISSUE TITLE
Suddenly need make + g++ to build duckdb

### ISSUE THREAD

**Issue by srenatus** [duckdb/duckdb-node#46]
Hey there!

During an `npm install` of a project that uses duckdb, I've suddenly got build failures. They indicate that the binary wasn't found, and needs to be build. Since I had been lacking the tools to do so in the container, it failed.

```
3248 timing build:link Completed in 70ms
3249 info run duckdb@0.9.2 install node_modules/duckdb node-pre-gyp install --fallback-to-build
3250 info run lz4@0.6.5 install node_modules/lz4 node-gyp rebuild
3251 info run sqlite3@5.1.5 install node_modules/sqlite3 node-pre-gyp install --fallback-to-build
3252 info run sqlite3@5.1.5 install { code: 0, signal: null }
3253 timing build:run:install:node_modules/sqlite3 Completed in 2926ms
3254 info run lz4@0.6.5 install { code: 1, signal: null }
3255 info run duckdb@0.9.2 install { code: 0, signal: null }
3256 timing build:run:install:node_modules/duckdb Completed in 14934ms
3257 timing reify:rollback:createSparse Completed in 12954ms
3258 timing reify:rollback:retireShallow Completed in 0ms
3259 timing command:i Completed in 41443ms
3260 verbose stack Error: command failed
3260 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
3260 verbose stack     at ChildProcess.emit (node:events:513:28)
3260 verbose stack     at maybeClose (node:internal/child_process:1091:16)
3260 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
3261 verbose pkgid lz4@0.6.5
3262 verbose cwd /w
3263 verbose Linux 6.5.13-orbstack-00122-g57b8027e2387
3264 verbose node v18.16.0
3265 verbose npm  v9.5.1
3266 error code 1
3267 error path /w/node_modules/lz4
3268 error command failed
3269 error command sh -c node-gyp rebuild
3270 error gyp info it worked if it ends with ok
3270 error gyp info using node-gyp@9.4.1
3270 error gyp info using node@18.16.0 | linux | x64
3270 error gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
3270 error gyp http GET https://nodejs.org/download/release/v18.16.0/node-v18.16.0-headers.tar.gz
3270 error gyp http 200 https://nodejs.org/download/release/v18.16.0/node-v18.16.0-headers.tar.gz
3270 error gyp http GET https://nodejs.org/download/release/v18.16.0/SHASUMS256.txt
3270 error gyp http 200 https://nodejs.org/download/release/v18.16.0/SHASUMS256.txt
3270 error gyp info spawn /usr/bin/python3
3270 error gyp info spawn args [
3270 error gyp info spawn args   '/w/node_modules/node-gyp/gyp/gyp_main.py',
3270 error gyp info spawn args   'binding.gyp',
3270 error gyp info spawn args   '-f',
3270 error gyp info spawn args   'make',
3270 error gyp info spawn args   '-I',
3270 error gyp info spawn args   '/w/node_modules/lz4/build/config.gypi',
3270 error gyp info spawn args   '-I',
3270 error gyp info spawn args   '/w/node_modules/node-gyp/addon.gypi',
3270 error gyp info spawn args   '-I',
3270 error gyp info spawn args   '/root/.cache/node-gyp/18.16.0/include/node/common.gypi',
3270 error gyp info spawn args   '-Dlibrary=shared_library',
3270 error gyp info spawn args   '-Dvisibility=default',
3270 error gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.16.0',
3270 error gyp info spawn args   '-Dnode_gyp_dir=/w/node_modules/node-gyp',
3270 error gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.16.0/<(target_arch)/node.lib',
3270 error gyp info spawn args   '-Dmodule_root_dir=/w/node_modules/lz4',
3270 error gyp info spawn args   '-Dnode_engine=v8',
3270 error gyp info spawn args   '--depth=.',
3270 error gyp info spawn args   '--no-parallel',
3270 error gyp info spawn args   '--generator-output',
3270 error gyp info spawn args   'build',
3270 error gyp info spawn args   '-Goutput_dir=.'
3270 error gyp info spawn args ]
3270 error gyp ERR! build error 
3270 error gyp ERR! stack Error: not found: make
3270 error gyp ERR! stack     at getNotFoundError (/w/node_modules/which/which.js:10:17)
3270 error gyp ERR! stack     at /w/node_modules/which/which.js:57:18
3270 error gyp ERR! stack     at new Promise (<anonymous>)
3270 error gyp ERR! stack     at step (/w/node_modules/which/which.js:54:21)
3270 error gyp ERR! stack     at /w/node_modules/which/which.js:71:22
3270 error gyp ERR! stack     at new Promise (<anonymous>)
3270 error gyp ERR! stack     at subStep (/w/node_modules/which/which.js:69:33)
3270 error gyp ERR! stack     at /w/node_modules/which/which.js:80:22
3270 error gyp ERR! stack     at /w/node_modules/isexe/index.js:42:5
3270 error gyp ERR! stack     at /w/node_modules/isexe/mode.js:8:5
3270 error gyp ERR! System Linux 6.5.13-orbstack-00122-g57b8027e2387
3270 error gyp ERR! command "/usr/local/bin/node" "/w/node_modules/.bin/node-gyp" "rebuild"
3270 error gyp ERR! cwd /w/node_modules/lz4
3270 error gyp ERR! node -v v18.16.0
3270 error gyp ERR! node-gyp -v v9.4.1
3270 error gyp ERR! not ok
3271 verbose exit 1
```

This wasn't run on any non-mainstream architecture (linux/amd64), so I'm wondering what happened. I've noticed an open PR about the S3 bucket #30 (and #8), could it be that the previous bucket was cleaned out? 🤔 

Thank you! 🎈

**Comment by carlopi** [comment]
Can you try again with https://www.npmjs.com/package/duckdb/v/0.10.0 ?

**Comment by srenatus** [comment]
🎉 All is well with duckdb@0.10.0:
```
$ npm install duckdb@0.10.0
...
...
...
npm info run duckdb@0.10.0 install node_modules/duckdb node-pre-gyp install --fallback-to-build
npm info run duckdb@0.10.0 install { code: 0, signal: null }

added 112 packages in 14s

6 packages are looking for funding
  run `npm fund` for details
npm info ok
```

Thanks a lot! 👏
